"""
api/agents/graph.py
===================
Shared LangGraph utilities for all Nexus-AI agents.

This module is the ONLY place that sets up checkpointing and agent run logging.
Every agent (lead_agent, followup_agent, reporter_agent) imports from here.
This file never imports from any specific agent — dependency flows one way only.

What lives here:
  - get_checkpointer()   — async context manager yielding a SqliteSaver
  - log_agent_start()    — inserts an agent_runs row at run start
  - log_agent_complete() — updates the agent_runs row when run finishes
  - build_graph()        — wires a StateGraph from nodes + edges and compiles it
"""

import json
import logging
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import AsyncGenerator
from uuid import uuid4

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import StateGraph, END  # noqa: F401 — re-exported for agents

from api.config import get_settings
from api.database import get_db

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# SqliteSaver checkpointer
# ---------------------------------------------------------------------------

@asynccontextmanager
async def get_checkpointer() -> AsyncGenerator:
    """
    Async context manager that yields a SqliteSaver checkpointer.

    SqliteSaver persists every LangGraph step (node input/output) to SQLite,
    making agent runs resumable after a crash and inspectable after completion.

    Why a context manager? SqliteSaver holds a sqlite3 connection that must be
    closed cleanly, especially in long-running FastAPI processes.

    Usage:
        async with get_checkpointer() as checkpointer:
            graph = build_graph(..., checkpointer=checkpointer)
            result = await graph.ainvoke(state, config=...)
    """
    try:
        from langgraph.checkpoint.sqlite import SqliteSaver
        db_path = get_settings().sqlite_db_path
        # SqliteSaver.from_conn_string() creates its own checkpoint tables
        # automatically — it will not conflict with our 4 application tables.
        checkpointer = SqliteSaver.from_conn_string(db_path)
        logger.debug("SqliteSaver checkpointer opened at %s", db_path)
        yield checkpointer
    except ImportError:
        # langgraph.checkpoint.sqlite may not be available in all versions.
        # Fall back to MemorySaver so agents still run — just without persistence.
        logger.warning(
            "langgraph.checkpoint.sqlite not available — falling back to MemorySaver. "
            "Upgrade langgraph if you need checkpoint persistence."
        )
        yield MemorySaver()
    finally:
        logger.debug("SqliteSaver checkpointer closed")


# ---------------------------------------------------------------------------
# Agent run logging helpers
# ---------------------------------------------------------------------------

async def log_agent_start(agent_name: str, run_id: str, input_data: dict) -> str:
    """
    Insert a row into agent_runs with status='running'.

    Called at the very beginning of every agent's public function, before the
    graph is invoked. This ensures we have a record even if the graph crashes.

    Args:
        agent_name: Human-readable agent identifier, e.g. 'lead_classifier'.
        run_id:     UUID string generated by the public function. Stored as
                    UNIQUE in agent_runs so traces are always findable by it.
        input_data: The initial state dict passed to the graph. Serialised to
                    JSON here so the caller doesn't have to think about it.

    Returns:
        The auto-generated `id` (UUID) of the inserted row.
        Needed by log_agent_complete() to update the correct row.
    """
    row_id = str(uuid4())
    input_json = json.dumps(input_data, default=str)  # default=str handles datetimes

    async with get_db() as db:
        await db.execute(
            """
            INSERT INTO agent_runs (id, agent_name, run_id, input_json, status)
            VALUES (?, ?, ?, ?, 'running')
            """,
            (row_id, agent_name, run_id, input_json),
        )
        await db.commit()

    logger.info("Agent run started | agent=%s | run_id=%s | row_id=%s", agent_name, run_id, row_id)
    return row_id


async def log_agent_complete(
    row_id: str,
    output_data: dict,
    status: str = "completed",
) -> None:
    """
    Update the agent_runs row when a run finishes (success or failure).

    Called in the finally block of every agent's public function so that even
    failed runs are recorded with status='failed' rather than left as 'running'.

    Args:
        row_id:      The id returned by log_agent_start().
        output_data: The final state dict returned by the graph. Serialised to JSON.
        status:      'completed' | 'failed'. Defaults to 'completed'.
    """
    output_json = json.dumps(output_data, default=str)
    completed_at = datetime.now(timezone.utc).isoformat()

    async with get_db() as db:
        await db.execute(
            """
            UPDATE agent_runs
            SET output_json = ?, status = ?, completed_at = ?
            WHERE id = ?
            """,
            (output_json, status, completed_at, row_id),
        )
        await db.commit()

    logger.info("Agent run %s | row_id=%s", status, row_id)


# ---------------------------------------------------------------------------
# Graph builder helper
# ---------------------------------------------------------------------------

def build_graph(
    state_schema,
    nodes: list[tuple[str, callable]],
    edges: list[tuple[str, str]],
    entry_point: str,
) -> object:
    """
    Wire and compile a LangGraph StateGraph from declarative specs.

    This helper keeps agent files clean — they declare WHAT the graph is
    (nodes + edges) without repeating the same boilerplate add/compile calls.

    Uses MemorySaver for in-process checkpointing during a single request.
    Persistence across requests is handled by our agent_runs table via
    log_agent_start() / log_agent_complete().

    Args:
        state_schema: The TypedDict class that defines the graph's state shape.
        nodes:        List of (name, async_function) tuples. Each function takes
                      a state dict and returns a partial state dict with updates.
        edges:        List of (from_node, to_node) tuples for linear flow.
                      Use graph.add_conditional_edges() directly for branching.
        entry_point:  Name of the first node to run.

    Returns:
        A compiled LangGraph graph ready for `await graph.ainvoke(state, config=...)`.

    Example:
        graph = build_graph(
            state_schema=LeadState,
            nodes=[("classify_intent", classify_intent), ("score_lead", score_lead)],
            edges=[("classify_intent", "score_lead"), ("score_lead", END)],
            entry_point="classify_intent",
        )
    """
    builder = StateGraph(state_schema)

    # Register all nodes
    for name, fn in nodes:
        builder.add_node(name, fn)
        logger.debug("Graph node registered: %s", name)

    # Wire all edges
    for from_node, to_node in edges:
        builder.add_edge(from_node, to_node)

    # Set graph entry point
    builder.set_entry_point(entry_point)

    # Compile with in-memory checkpointer
    # MemorySaver keeps the thread state alive for the duration of a single
    # process — sufficient for stateless HTTP requests.
    compiled = builder.compile(checkpointer=MemorySaver())
    logger.debug("Graph compiled | entry_point=%s | nodes=%d", entry_point, len(nodes))
    return compiled